### PR TITLE
feat: delete and unpublish

### LINKED ISSUE #76: Delete and Unpublish
If a page no longer has a source document, it should be possible for authors to remove its renditions in preview and live (effectively unpublishing it).

If a missing source document is detected in..
- Preview: _Reload_ and _Publish_ plugins should be hidden, _Delete_ plugin should be shown
- Live: _Publish_ should be hidden,  _Delete_ plugin should be shown

When clicked and confirmed by the user, all renditions will be removed.

### PR DESCRIPTION
**Pull request by rofe**
Fix #76

### CODE REVIEW

**Review by kptdobe — APPROVED** [review]
Aas long as both require that the source document has been deleted, it really feels unpublish and delete are the same thing.

**Comment by rofe** [comment]
Right, Delete is a superset of Unpublish, which only deletes the live version. For now, both require that the source document has been deleted, but in an authenticated future, i imagine Unpublish will we possible with existing source documents and preview pages, so I'd keep the 2 actions separate.

**Comment by rofe** [comment]
But you bring up a good point: Delete currently only deletes the preview version, but it should also delete the live version (if one exists), implicitly unpublishing the page.

**Review by davidnuescheler — APPROVED** [review]

**Pull request merged**
